#include <ATen/mklrng/MKLGeneratorImpl.h>
#include <ATen/Utils.h>
#include <c10/util/MathConstants.h>
#include <algorithm>
#include <cstdint>

namespace at {
namespace detail {

/**
 * PyTorch maintains a collection of default generators that get
 * initialized once. The purpose of these default generators is to
 * maintain a global running state of the pseudo random number generation,
 * when a user does not explicitly mention any generator.
 * getDefaultMKLGenerator gets the default generator for a particular
 * device.
 */
const Generator& getDefaultMKLGenerator() {
  static auto gen = createMKLGenerator(c10::detail::getNonDeterministicRandom());
  return gen;
}

/**
 * Utility to create an MKLGeneratorImpl. Returns a shared_ptr
 */
Generator createMKLGenerator(uint64_t seed_val) {
  return make_generator<MKLGeneratorImpl>(seed_val);
}

} // namespace detail

/**
 * MKLGeneratorImpl class implementation
 */
MKLGeneratorImpl::MKLGeneratorImpl(uint64_t seed_in)
  : c10::GeneratorImpl{Device(DeviceType::CPU), DispatchKeySet(c10::DispatchKey::CPU)},
    seed_(seed_in),
    offset_(0),
    lock_seed_(false) {
    vslNewStream(&stream_, VSL_BRNG_MCG59, seed_);
  }

/**
 * Manually seeds the engine with the seed input
 * See Note [Acquire lock when using random generators]
 */
void MKLGeneratorImpl::set_current_seed(uint64_t seed) {
  this->seed_ = seed;
  vslDeleteStream(&stream_);
  vslNewStream(&stream_, VSL_BRNG_MCG59, seed_);
  this->offset_ = 0;
}

/**
 * Gets a nondeterministic random number from /dev/urandom or time,
 * seeds the MKLGeneratorImpl with it and then returns that number.
 * See Note [Acquire lock when using random generators]
 */
uint64_t MKLGeneratorImpl::seed() {
  auto random = c10::detail::getNonDeterministicRandom();
  this->set_current_seed(static_cast<uint64_t>(random));
  return random;
}

/**
 * Gets the current seed of CPUGeneratorImpl.
 */
uint64_t MKLGeneratorImpl::current_seed() const {
  return this->seed_;
}

/**
 * Sets the lock_seed_ flag of MKLGenerator.
 * See Note [Acquire lock when using random generators]
 *
 * The MKLGenerator uses lock_seed_ as a flag to denote whether
 * it was already initialised with a seed from CPUGenerator in order to
 * avoid the issue in https://github.com/pytorch/pytorch/issues/132395.
 */
void MKLGeneratorImpl::set_lock_seed(bool lock_seed) {
  this->lock_seed_ = lock_seed;
}

/**
 * Gets the lock_seed_ flag of MKLGenerator.
 */
bool MKLGeneratorImpl::get_lock_seed() const {
  return this->lock_seed_;
}

/**
 * Gets the DeviceType of MKLGeneratorImpl.
 * Used for type checking during run time.
 */
DeviceType MKLGeneratorImpl::device_type() {
  return DeviceType::CPU;
}

/**
 * Gets the copy of VSLStreamStatePtr in MKLGenerator
 * to be used for variate generation in a thread-safe way
 * (each thread should receive its own stream copy).
 * See Note [Acquire lock when using random generators]
 */
void MKLGeneratorImpl::get_stream_copy(VSLStreamStatePtr &streamCopy) {
  vslCopyStream(&streamCopy, stream_);
}

/**
 * Progresses the internal PRNG state n steps ahead -- 
 * used to account for variates generated by the copies
 * of the stream in MKLGenerator.
 * See Note [Acquire lock when using random generators]
 */
void MKLGeneratorImpl::skip_ahead(uint64_t n) {
  vslSkipAheadStream(stream_, n);
  this->advance_offset(n);
}

/**
 * Private clone method implementation
 * See Note [Acquire lock when using random generators]
 */
MKLGeneratorImpl* MKLGeneratorImpl::clone_impl() const {
  auto gen = new MKLGeneratorImpl();
  return gen;
}

/**
 * Public clone method implementation
 * See Note [Acquire lock when using random generators]
 */
std::shared_ptr<MKLGeneratorImpl> MKLGeneratorImpl::clone() const {
  return std::shared_ptr<MKLGeneratorImpl>(this->clone_impl());
}

/**
 * Sets the offset of RNG state.
 * See Note [Acquire lock when using random generators]
 */
void MKLGeneratorImpl::set_offset(uint64_t offset) {
  TORCH_CHECK(false, "MKL Generator does not support directly setting offset");
}

/**
 * Gets the offset of RNG state.
 * See Note [Acquire lock when using random generators]
 */
uint64_t MKLGeneratorImpl::get_offset() const {
  return this->offset_;
}

/**
 * Private method to advance the offset of RNG state.
 * See Note [Acquire lock when using random generators]
 */
void MKLGeneratorImpl::advance_offset(uint64_t n) {
  this->offset_ += n;
}

/**
 * Gets the current internal state of MKLGeneratorImpl. The internal
 * state is returned as a CPU byte tensor.
 */
c10::intrusive_ptr<c10::TensorImpl> MKLGeneratorImpl::get_state() const {
  static const size_t seed_size = sizeof(uint64_t);
  static const size_t offset_size = sizeof(uint64_t);
  static const size_t lock_seed_size = sizeof(bool);
  static const size_t total_size = seed_size + offset_size + lock_seed_size;

  auto state_tensor = at::detail::empty_cpu({(int64_t)total_size}, ScalarType::Byte, std::nullopt, std::nullopt, std::nullopt, std::nullopt);
  auto rng_state = state_tensor.data_ptr<uint8_t>();
  auto current_seed = this->current_seed();
  auto current_offset = this->get_offset();
  auto current_lock_seed = this->get_lock_seed();

  memcpy(rng_state, &current_seed, seed_size);
  memcpy(rng_state+seed_size, &current_offset, offset_size);
  memcpy(rng_state+seed_size+offset_size, &current_lock_seed, lock_seed_size);

  return state_tensor.getIntrusivePtr();
}

/**
 * Sets the internal state of MKLGeneratorImpl. The new internal state
 * must be a strided CPU byte tensor.
 */
 void MKLGeneratorImpl::set_state(const c10::TensorImpl& new_state) {
  static const size_t seed_size = sizeof(uint64_t);
  static const size_t offset_size = sizeof(uint64_t);
  static const size_t lock_seed_size = sizeof(bool);
  static const size_t total_size = seed_size + offset_size + lock_seed_size;

  detail::check_rng_state(new_state);

  auto new_state_size = new_state.numel();
  TORCH_CHECK(new_state_size == total_size, "RNG state is wrong size");

  uint64_t input_seed = 0;
  uint64_t input_offset = 0;
  bool input_lock_seed = 0;

  auto new_rng_state = new_state.data_dtype_initialized<uint8_t>();
  memcpy(&input_seed, new_rng_state, seed_size);
  memcpy(&input_offset, new_rng_state+seed_size, offset_size);
  memcpy(&input_lock_seed, new_rng_state+seed_size+offset_size, lock_seed_size);

  this->set_current_seed(input_seed);
  this->skip_ahead(input_offset);
  this->set_lock_seed(input_lock_seed);
}

} // namespace at
